import { useState } from 'react';
import { CheckCircle2, AlertTriangle, AlertCircle, FileText, Smartphone, Code, ShieldCheck, ArrowRight, Mail, X, RefreshCw } from 'lucide-react';

export default function Overview({ 
  overallScore, 
  copyScore, 
  visualScore, 
  techScore, 
  spamScore, 
  issuesCount, 
  setActiveTab,
  onRunAudit,
  isAuditing
}) {
  // SVG Config for Circular Progress Ring
  const radius = 80;
  const strokeWidth = 14;
  const normalizedRadius = radius - strokeWidth * 2;
  const circumference = normalizedRadius * 2 * Math.PI;
  const strokeDashoffset = circumference - (overallScore / 100) * circumference;

  const [showEmailModal, setShowEmailModal] = useState(false);
  const [recipientEmail, setRecipientEmail] = useState('');
  const [isSending, setIsSending] = useState(false);
  const [successSent, setSuccessSent] = useState(false);

  const getScoreColor = (score) => {
    if (score >= 90) return 'var(--success)';
    if (score >= 70) return 'var(--warning)';
    return 'var(--error)';
  };

  const handleSendEmail = (e) => {
    e.preventDefault();
    if (!recipientEmail) return;

    setIsSending(true);

    const subject = `OmniQA Campaign QA Report: ${overallScore}/100 Health Index`;
    const body = `OmniQA Campaign QA Audit Report
======================================
Recipient: ${recipientEmail}
Overall Health Score: ${overallScore}/100

[Audit Breakdown]
- Copy Sync Score: ${copyScore}% (${issuesCount.high} high / ${issuesCount.medium} medium mismatches)
- Visual Code Score: ${visualScore}%
- Liquid & Link Health: ${techScore}%
- Spam Filter Score: ${spamScore}%

[Technical Summary]
- Total Audited Issues: ${issuesCount.high + issuesCount.medium + issuesCount.low} flags checked.

Please review the OmniQA dashboard to inspect figma copy diffs and apply auto-fixes to UTM links.

Generated by OmniQA for Braze.`;

    const mailtoUrl = `mailto:${recipientEmail}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    
    // Simulate API network latency
    setTimeout(() => {
      setIsSending(false);
      setSuccessSent(true);
      window.location.href = mailtoUrl;
    }, 1500);
  };

  return (
    <div className="fade-in">
      <div style={{ display: 'grid', gridTemplateColumns: '1.2fr 2fr', gap: '2rem', marginBottom: '2rem' }}>
        
        {/* Left Side: Radial Gauge Panel */}
        <div className="panel" style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', minHeight: '340px' }}>
          <h3 style={{ marginBottom: '1.5rem', textAlign: 'center' }}>Campaign Health</h3>
          
          <div className="progress-ring-container">
            <svg height={radius * 2} width={radius * 2}>
              {/* Background Track */}
              <circle
                stroke="rgba(255,255,255,0.03)"
                fill="transparent"
                strokeWidth={strokeWidth}
                r={normalizedRadius}
                cx={radius}
                cy={radius}
              />
              {/* Foreground Glow */}
              <circle
                stroke={getScoreColor(overallScore)}
                fill="transparent"
                strokeWidth={strokeWidth}
                strokeDasharray={circumference + ' ' + circumference}
                style={{ strokeDashoffset }}
                strokeLinecap="round"
                r={normalizedRadius}
                cx={radius}
                cy={radius}
                className="progress-ring-circle"
              />
            </svg>
            <div className="progress-ring-text">
              <span>{overallScore}</span>
              <span className="progress-ring-label">Health Index</span>
            </div>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem', width: '100%', marginTop: '2rem' }}>
            <button 
              className="btn btn-primary" 
              style={{ width: '100%' }}
              onClick={onRunAudit}
              disabled={isAuditing}
            >
              {isAuditing ? 'Analyzing Campaign...' : 'Re-Run QA Audit'}
            </button>
            
            <button 
              className="btn btn-secondary" 
              style={{ width: '100%', display: 'flex', alignItems: 'center', gap: '0.4rem', justifyContent: 'center' }}
              onClick={() => {
                setShowEmailModal(true);
                setSuccessSent(false);
                setRecipientEmail('');
              }}
              disabled={isAuditing}
            >
              <Mail size={16} /> Send Report via Email
            </button>

            <button 
              className="btn btn-secondary" 
              style={{ width: '100%', display: 'flex', alignItems: 'center', gap: '0.4rem', justifyContent: 'center', borderColor: 'var(--accent-cyan)', color: 'var(--accent-cyan)' }}
              onClick={() => window.print()}
              disabled={isAuditing}
            >
              <Sparkles size={14} /> Download PDF Report
            </button>
          </div>
        </div>

        {/* Right Side: Score Summary & Severity breakdown */}
        <div className="panel" style={{ display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
          <div>
            <h3 style={{ marginBottom: '0.25rem' }}>Automated Audit Results</h3>
            <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', marginBottom: '1.5rem' }}>
              OmniQA has cross-referenced Figma design assets against your coded HTML campaign body and Liquid attributes.
            </p>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '1rem', marginBottom: '1.5rem' }}>
              <div style={{ padding: '1rem', backgroundColor: 'var(--bg-tertiary)', borderRadius: 'var(--border-radius-md)', border: '1px solid var(--border-color)', display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                <AlertCircle size={24} style={{ color: 'var(--error)' }} />
                <div>
                  <div style={{ fontSize: '1.25rem', fontWeight: '700' }}>{issuesCount.high}</div>
                  <div style={{ fontSize: '0.75rem', color: 'var(--text-secondary)' }}>High Severity</div>
                </div>
              </div>
              
              <div style={{ padding: '1rem', backgroundColor: 'var(--bg-tertiary)', borderRadius: 'var(--border-radius-md)', border: '1px solid var(--border-color)', display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                <AlertTriangle size={24} style={{ color: 'var(--warning)' }} />
                <div>
                  <div style={{ fontSize: '1.25rem', fontWeight: '700' }}>{issuesCount.medium}</div>
                  <div style={{ fontSize: '0.75rem', color: 'var(--text-secondary)' }}>Medium Severity</div>
                </div>
              </div>

              <div style={{ padding: '1rem', backgroundColor: 'var(--bg-tertiary)', borderRadius: 'var(--border-radius-md)', border: '1px solid var(--border-color)', display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                <CheckCircle2 size={24} style={{ color: 'var(--success)' }} />
                <div>
                  <div style={{ fontSize: '1.25rem', fontWeight: '700' }}>{issuesCount.low}</div>
                  <div style={{ fontSize: '0.75rem', color: 'var(--text-secondary)' }}>Low Severity</div>
                </div>
              </div>
            </div>
          </div>

          <div style={{ borderTop: '1px solid var(--border-color)', paddingTop: '1.25rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <span style={{ fontSize: '0.9rem', color: 'var(--text-secondary)' }}>
              {issuesCount.high + issuesCount.medium === 0 
                ? '🎉 Campaign is in perfect shape to deploy!' 
                : `⚠️ Found ${issuesCount.high + issuesCount.medium} issues requiring attention.`}
            </span>
            <span style={{ fontSize: '0.85rem', color: 'var(--accent-blue)', display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
              Checked 6 standard deliverables <CheckCircle2 size={14} style={{ color: 'var(--success)' }} />
            </span>
          </div>
        </div>

      </div>

      {/* Grid of Categories */}
      <h3 style={{ marginBottom: '1rem' }}>Audit Categories</h3>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.25rem' }}>
        
        {/* Copy sync */}
        <div className="category-card" onClick={() => setActiveTab('copy')}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
            <div className="category-icon-bg" style={{ backgroundColor: 'rgba(59, 130, 246, 0.08)', color: 'var(--accent-blue)' }}>
              <FileText size={20} />
            </div>
            <div>
              <h4 style={{ fontSize: '1rem', marginBottom: '0.15rem' }}>Copy & Content Auditor</h4>
              <p style={{ color: 'var(--text-secondary)', fontSize: '0.8rem' }}>Figma extraction text vs Braze HTML tags</p>
            </div>
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <span className="category-score" style={{ color: getScoreColor(copyScore) }}>{copyScore}%</span>
            <ArrowRight size={16} style={{ color: 'var(--text-muted)' }} />
          </div>
        </div>

        {/* Visual stress */}
        <div className="category-card" onClick={() => setActiveTab('visuals')}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
            <div className="category-icon-bg" style={{ backgroundColor: 'rgba(139, 92, 246, 0.08)', color: 'var(--accent-purple)' }}>
              <Smartphone size={20} />
            </div>
            <div>
              <h4 style={{ fontSize: '1rem', marginBottom: '0.15rem' }}>Visual Stress-Tester</h4>
              <p style={{ color: 'var(--text-secondary)', fontSize: '0.8rem' }}>Renders customization fallbacks & previews</p>
            </div>
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <span className="category-score" style={{ color: getScoreColor(visualScore) }}>{visualScore}%</span>
            <ArrowRight size={16} style={{ color: 'var(--text-muted)' }} />
          </div>
        </div>

        {/* Code & liquid */}
        <div className="category-card" onClick={() => setActiveTab('technical')}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
            <div className="category-icon-bg" style={{ backgroundColor: 'rgba(6, 182, 212, 0.08)', color: 'var(--accent-cyan)' }}>
              <Code size={20} />
            </div>
            <div>
              <h4 style={{ fontSize: '1rem', marginBottom: '0.15rem' }}>Liquid & Link Health</h4>
              <p style={{ color: 'var(--text-secondary)', fontSize: '0.8rem' }}>Liquid parsing, dead URL checks, UTM tags</p>
            </div>
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <span className="category-score" style={{ color: getScoreColor(techScore) }}>{techScore}%</span>
            <ArrowRight size={16} style={{ color: 'var(--text-muted)' }} />
          </div>
        </div>

        {/* Deliverability & WCAG */}
        <div className="category-card" onClick={() => setActiveTab('technical')}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
            <div className="category-icon-bg" style={{ backgroundColor: 'rgba(16, 185, 129, 0.08)', color: 'var(--success)' }}>
              <ShieldCheck size={20} />
            </div>
            <div>
              <h4 style={{ fontSize: '1rem', marginBottom: '0.15rem' }}>Spam & WCAG Auditing</h4>
              <p style={{ color: 'var(--text-secondary)', fontSize: '0.8rem' }}>Calculates contrast ratio & filters spam triggers</p>
            </div>
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <span className="category-score" style={{ color: getScoreColor(spamScore) }}>{spamScore}%</span>
            <ArrowRight size={16} style={{ color: 'var(--text-muted)' }} />
          </div>
        </div>

      </div>

      {/* EMAIL MODAL OVERLAY */}
      {showEmailModal && (
        <div 
          style={{
            position: 'fixed',
            top: 0,
            left: 0,
            width: '100vw',
            height: '100vh',
            background: 'rgba(5, 8, 15, 0.95)',
            zIndex: 1000,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            backdropFilter: 'blur(10px)',
            animation: 'fadeIn 0.25s ease-out'
          }}
        >
          <div 
            style={{
              background: 'var(--bg-secondary)',
              border: '1px solid var(--border-color)',
              padding: '2.5rem 2rem 2rem 2rem',
              borderRadius: 'var(--border-radius-lg)',
              position: 'relative',
              width: '90%',
              maxWidth: '450px',
              display: 'flex',
              flexDirection: 'column',
              boxShadow: '0 25px 60px rgba(0,0,0,0.8)'
            }}
          >
            <button 
              onClick={() => setShowEmailModal(false)}
              style={{
                position: 'absolute',
                top: '1rem',
                right: '1rem',
                background: 'rgba(255,255,255,0.03)',
                border: '1px solid var(--border-color)',
                borderRadius: '50%',
                width: '36px',
                height: '36px',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                color: 'var(--text-primary)',
                cursor: 'pointer',
                transition: 'all 0.15s ease'
              }}
            >
              <X size={18} />
            </button>

            <h3 style={{ marginBottom: '0.5rem', display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--text-primary)' }}>
              <Mail size={22} style={{ color: 'var(--accent-cyan)' }} /> Send Campaign QA Report
            </h3>
            <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem', marginBottom: '1.5rem' }}>
              Deliver the complete copy, visual, and technical diagnostics audit to your inbox.
            </p>

            {successSent ? (
              <div style={{ textAlign: 'center', padding: '1.5rem 0' }}>
                <CheckCircle2 size={48} style={{ color: 'var(--success)', marginBottom: '1rem', display: 'inline-block' }} />
                <h4 style={{ color: 'var(--text-primary)', marginBottom: '0.25rem' }}>Report Dispatched Successfully!</h4>
                <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem' }}>
                  A detailed HTML report has been sent to <strong style={{ color: 'var(--text-primary)' }}>{recipientEmail}</strong>.
                </p>
                <button 
                  className="btn btn-secondary" 
                  onClick={() => setShowEmailModal(false)}
                  style={{ marginTop: '1.5rem', width: '100%' }}
                >
                  Close Panel
                </button>
              </div>
            ) : (
              <form onSubmit={handleSendEmail} style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
                <div className="form-group" style={{ margin: 0 }}>
                  <label className="form-label">Recipient Email Address</label>
                  <input 
                    type="email" 
                    required 
                    className="form-input" 
                    placeholder="name@company.com" 
                    value={recipientEmail} 
                    onChange={(e) => setRecipientEmail(e.target.value)}
                    disabled={isSending}
                    style={{ background: 'var(--bg-tertiary)' }}
                  />
                </div>

                <div style={{ padding: '1rem', backgroundColor: 'var(--bg-tertiary)', borderRadius: 'var(--border-radius-md)', border: '1px solid var(--border-color)', fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
                  <strong style={{ color: 'var(--accent-cyan)' }}>Report Contents:</strong>
                  <ul style={{ paddingLeft: '1.25rem', marginTop: '0.35rem', display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
                    <li>Overall Campaign Health Score: <strong>{overallScore}/100</strong></li>
                    <li>Copy Sync Mismatches detected: <strong>{issuesCount.high + issuesCount.medium}</strong></li>
                    <li>WCAG Contrast and HTML validation metrics</li>
                    <li>Deliverability & Spam analysis</li>
                  </ul>
                </div>

                <button 
                  type="submit" 
                  className="btn btn-primary" 
                  style={{ width: '100%' }} 
                  disabled={isSending}
                >
                  {isSending ? (
                    <>
                      <RefreshCw size={14} className="spin" style={{ marginRight: '0.25rem' }} /> Dispatching Report...
                    </>
                  ) : (
                    'Send QA Report'
                  )}
                </button>
              </form>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
